Removing trust in codecov bash uploader, checking hashes

diff --git a/.github/workflows/rust.yml b/.github/workflows/rust.yml
--- a/.github/workflows/rust.yml
+++ b/.github/workflows/rust.yml
@@ -83,4 +83,26 @@ jobs:
           cargo test --verbose $CARGO_OPTIONS
           zip -0 ccov.zip `find . \( -name "big_primes*.gc*" \) -print`; 
           ./grcov ccov.zip -s . -t lcov --llvm --branch --ignore-not-existing --ignore "/*" -o lcov.info;
-          bash <(curl -s https://codecov.io/bash) -f lcov.info;
+          # validate and then run codecov bash uploader
+          FILENAME=codecov
+          curl -s https://codecov.io/bash > $FILENAME
+          CODECOV_VERSION=$(grep -o 'VERSION=\"[0-9\.]*\"' codecov | cut -d'"' -f2);
+          VALIDATION_FAILURE=0
+          for i in 1 256 512
+          do
+            IS_DIFF=$(diff <(shasum -a $i $FILENAME) <(curl -s https://raw.githubusercontent.com/codecov/codecov-bash/$CODECOV_VERSION/SHA${i}SUM))
+            if [ -z "${IS_DIFF}" ]; then
+              echo "Sha:" $i "passes validation."
+            else
+              VALIDATION_FAILURE=1
+            fi
+          done
+          if [ "${VALIDATION_FAILURE}" == 1 ]; then
+            echo "Invalid Checksum Detected From Codecov. Quitting."
+            exit 1
+          else
+            echo "Starting Codecov."
+            chmod +x codecov
+            ./codecov -f lcov.info;
+          fi
+          rm -rf $FILENAME
